[target.mips-unknown-linux-musl]
linker = "rust-lld"
rustflags = [
    "-C", "target-feature=+soft-float",
    "-C", "linker-flavor=ld.lld",
    "-C", "link-arg=-L/home/patkepa/.local/mips-linux-musl-cross/mips-linux-musl/lib",
    "-C", "link-arg=-L/home/patkepa/.local/mips-linux-musl-cross/lib/gcc/mips-linux-musl/11.2.1",
]
